name: Docker Build
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and Publish to Dockerhub
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: hirsutehippo
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: latest
